# name: Call TCU API on dashboard commit

# on:
#   push:
#     branches:
#       - main

# jobs:
#   call-api:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Hit TCU Endpoint
#         run: |
#           curl --fail --silent --show-error \
#                -X GET "${{ secrets.tcu_endpoint }}/pull-code" \
#                -H "Content-Type: application/json"

name: Deploy to EC2 on Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t myapp:latest .
      
      - name: Debug Docker Username
        run: echo "DOCKER_USER is ${{ secrets.DOCKER_USER }}"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Push to Docker Hub
        run: |
          docker tag myapp:latest ${{ secrets.DOCKER_USER }}/myapp:latest
          docker push ${{ secrets.DOCKER_USER }}/myapp:latest

      - name: Hit TCU Endpoint
        run: |
          curl --fail --silent --show-error \
               -X GET "${{ secrets.tcu_endpoint }}/pull-code" \
               -H "Content-Type: application/json"
